[package]
name = "sg-workflow"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sg-provenance = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sg-store = { workspace = true }
rusqlite = { workspace = true }
sha2 = { workspace = true }
time = { workspace = true }
sg-policy = { workspace = true }
sg-integrations = { workspace = true }
